### PR TITLE
Bokeh images. Add catalog

### PR DESCRIPTION
**Pull request by dsavchenko**
Plotting in plugin. Catalog. Use oda data-products wherever possible.

### CODE REVIEW

**Comment by dsavchenko** [comment]
@andriineronov what columns of the Legacy Survey catalogue we want to show in the frontend?

**Comment by dsavchenko** [comment]
js9 plot is not working, ending up in the exception https://github.com/oda-hub/dispatcher-app/blob/be29336f311bc2e5b7d4a994309b5c110f4a7115/cdci_data_analysis/flask_app/app.py#L488 
The image .fits file is there and download is working.

@volodymyrss what am I doing wrong?

**Comment by dsavchenko** [comment]
Cosmetic issues:
1. It is not possible to plot with log-normed colormap.
2. Would be good to reduce the radius of source circles.

Both require changes in dispatcher-app plot_tools.py

**Comment by volodymyrss** [comment]
> js9 plot is not working, ending up in the exception https://github.com/oda-hub/dispatcher-app/blob/be29336f311bc2e5b7d4a994309b5c110f4a7115/cdci_data_analysis/flask_app/app.py#L488 The image .fits file is there and download is working.
> 
> @volodymyrss what am I doing wrong?

so what's the `e` in https://github.com/oda-hub/dispatcher-app/blob/be29336f311bc2e5b7d4a994309b5c110f4a7115/cdci_data_analysis/flask_app/app.py#L488 ?

**Comment by volodymyrss** [comment]
> Cosmetic issues:
> 
>     1. It is not possible to plot with log-normed colormap.
> 
>     2. Would be good to reduce the radius of source circles.
> 
> 
> Both require changes in dispatcher-app plot_tools.py

both are achievable easily enouch with the change in `dispatcher-app plot_tools.py` if so, could be worth it.

In any case, could you share the screenshot, how does it look now?

**Comment by dsavchenko** [comment]
> In any case, could you share the screenshot, how does it look now?

This is how it looks now for Mrk 421
Знімок екрану з 2022-02-08 19-02-25

This is how it may look with LogNorm
Знімок екрану з 2022-02-08 19-03-58

**Comment by dsavchenko** [comment]
> so what's the `e`

Ah, it is IndexError('list index out of range')
So maybe it is just about ext_id, which has 4 by default (why?) 
And the image is in extension 0

**Comment by volodymyrss** [comment]
> > In any case, could you share the screenshot, how does it look now?
> 
> This is how it looks now for Mrk 421 Знімок екрану з 2022-02-08 19-02-25
> 
> This is how it may look with LogNorm Знімок екрану з 2022-02-08 19-03-58

For the circle size I kind of prefer the first one, since the circles do not block the source pixels. Even  if many are kind of messy. But as you wish.

For the lognorm, can you not just make linear scale of log(X)? I.e. take the log yourself. the scale will then go from -2 to 1 (not 1e-2 - 1e1), but that's quite common.
A small dispatcher change would be just as fine, marginally more complex.

ext_id of 4 is integral thing. I guess it's hard-coded. Needs to be relaxed. Could you propose a fix?

**Comment by dsavchenko** [comment]
> For the circle size I kind of prefer the first one

I have no clear preference, so let's leave it like this.

> A small dispatcher change would be just as fine

Currently, the version of bokeh is fixed to the ancient one https://github.com/oda-hub/dispatcher-app/blob/be29336f311bc2e5b7d4a994309b5c110f4a7115/requirements.txt#L13
and it actually lacks LogColorMapper implementation (https://github.com/bokeh/bokeh/blob/7e4333b0e60c173983f44eab06d26c9255564213/bokeh/models/mappers.py#L126) 

Was there a reason to fix this particular version? Should we update to the latest one (requires some manual testing, of course)?
If so, I can fairly easy make a widget to switch between Linear-Log interactively.

**Comment by volodymyrss** [comment]
> > For the circle size I kind of prefer the first one
> 
> I have no clear preference, so let's leave it like this.
> 
> > A small dispatcher change would be just as fine
> 
> Currently, the version of bokeh is fixed to the ancient one https://github.com/oda-hub/dispatcher-app/blob/be29336f311bc2e5b7d4a994309b5c110f4a7115/requirements.txt#L13 and it actually lacks LogColorMapper implementation (https://github.com/bokeh/bokeh/blob/7e4333b0e60c173983f44eab06d26c9255564213/bokeh/models/mappers.py#L126)
> 
> Was there a reason to fix this particular version? Should we update to the latest one (requires some manual testing, of course)? If so, I can fairly easy make a widget to switch between Linear-Log interactively.

No idea if there is a reason or not. Let's try.

**Review by volodymyrss — APPROVED** [review]
we can add a test in the future. By the way, nb2service has some built-in mechanism to test the notebooks somewhat generically. We can use it then.

**Comment by dsavchenko** [comment]
Yes, I will add tests by separate PR.

> By the way, nb2service has some built-in mechanism to test the notebooks somewhat generically. We can use it then.

Will you show? Anyway, it is more suitable to the backend, I guess.

**Pull request merged**
